### ISSUE TITLE
CPU fries when trying to reset after gameover

### ISSUE THREAD

**Issue by joppiesaus** [joppiesaus/fps-snake#4]
It completely crashes.
Something happens, but I don't know what. It's something inside the `initSnake` function. All functions are getting returned however.

I'll figure it out eventually.

@waldenn plz fix xdd jkjk

**Comment by hzrd149** [comment]
there is an infinite loop at, [main.js line: 341](https://github.com/joppiesaus/fps-snake/blob/master/js/main.js#L341)

it occurs when **delta** is greater then 0.7
im not sure of your reasons for using that type of loop, but here is some suggestions
- test to see if delta is > 0.7
- use a different kind of loop (might not work, again i dont know what that part of the code is for so i cant say)

**Comment by joppiesaus** [comment]
I completely read over that.

The loop is _intended_ to work like this:
Current time += delta
while the current time > time required between each update,
--> update & current time -= time required between each update

I'll fix it ASAP

@rdfriedl Thank you so much. :star:
